name: Lint
on: [ push, pull_request ]
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run proselint
      uses: ./.github/actions/proselint
